### ISSUE TITLE
ℹ️ Add "Problem Research" markdown to repo

### ISSUE THREAD

**Issue by KenjiPcx** [KenjiPcx/Diabot#21]
**Important**: This is a deliverable for the project
Create a markdown file and consolidate all the problem research we have done, let's limit this to the problems we discovered in the scope of diabetes management apps

Create a file with the name "Problem Research.md"
### Things to include
- Current state of diabetes management apps
- Problems people face with diabetes apps

**Comment by lahybris** [comment]
We can include things such as: 

Diabetes management apps can be a useful tools for people with diabetes to help them manage their condition, but like any tool, they can also have their limitations. Some of the potential problems that people may face when using diabetes management apps include the following:

- Inaccurate or incomplete information: One potential problem with diabetes management apps is that they may not always provide accurate or complete information. For example, some apps may not have been validated or peer-reviewed, and the information they provide may not be reliable. Additionally, the information provided by the app may not be tailored to the user's specific needs, and may not take into account their individual medical history or other factors that may affect their diabetes management.

- Limited functionality: Another potential problem with diabetes management apps is that they may not offer all of the features and functionality that users need to effectively manage their diabetes. For example, some apps may only track blood sugar levels, while others may not provide tools for tracking or managing other important aspects of diabetes management, such as medication or exercise. As a result, users may need to use multiple apps to fully manage their condition, which can be inconvenient and time-consuming.

- Security and privacy concerns: Diabetes management apps may also raise concerns about security and privacy. For example, the app may collect sensitive personal and health information, such as blood sugar levels and medication data, which could be accessed by unauthorized parties if the app's security is not properly implemented. Additionally, the app may not have adequate privacy protections in place, which could expose users' personal and health information to potential misuse or abuse.

- User interface and usability issues: Finally, diabetes management apps may also have a user interface and usability issues that can make them difficult or frustrating to use. For example, the app may have a poorly designed user interface that is difficult to navigate, or it may be difficult for users to enter or view their data. Additionally, the app may not provide adequate instructions or support for users, which can make it difficult for them to properly use the app and manage their diabetes.

**Comment by KenjiPcx** [comment]
@lahybris Can you reformat this to look nicer use headers for starters, look at git flavoured markdown then we can close this
