### ISSUE TITLE
ℹ️ Add "Solution Identification" markdown to the repo

### ISSUE THREAD

**Issue by KenjiPcx** [KenjiPcx/Diabot#22]
**Important** : This is a deliverable for the project
Create a markdown file and include the solution ideas we have with Azure for diabetics management apps

Create a file with the name "Solution Identification.md"
### Things to include
- Solutions
- For each solution, we should include how Azure cloud can help
- What we chose in the end
- Why we chose it

**Comment by KenjiPcx** [comment]
### Solutions we can include
- Using Azure ML to fine tune the predicted glucose level to the person, retrain the model periodically with user data
- Using Azure ML to fine tune the insulin delivery plan (how often to inject), retrain it periodically with user data
- Using Azure Computer Vision to identify fast, medium and slow carbs from food pictures
- Using Azure DB to store commonly used recipes for carb planning
- Using Azure Bots to interact with the app, summarize charts, add carbs etc
- Using Azure Maps to remind users to record carbs (for example, when it detects that you are in a gym, it reminds you etc)
- Adding an Azure IoT interface towards continuous glucose monitors and insulin pumps

**Comment by lahybris** [comment]
Azure Machine Learning (ML) can be used to fine-tune the predicted glucose levels for individual users and retrain the model periodically with user data. This can help improve the accuracy of the predictions and make the insulin delivery plan more personalized and effective.

In addition, Azure Computer Vision can be used to identify the types of carbohydrates in food pictures, which can be useful for carb planning. Azure Database can be used to store commonly used recipes, and Azure Bots can be used to interact with the app and provide summaries and other information to users.

Azure Maps can also be integrated into the app to remind users to record their carbohydrate intake and provide other helpful reminders, such as when they are in a gym or other location where they may be more likely to need to manage their diabetes.

Finally, an Azure IoT interface can be added to connect the app to continuous glucose monitors and insulin pumps, allowing for even more accurate and personalized management of diabetes.

**Comment by KenjiPcx** [comment]
@lahybris Can we give some more context to this document, for example, include some details about what this page is for

# Solutions Identification
Here are some of the solutions we identified in month 2

### Using Azure ML to fine tune ...
The explaination 

etc
