### ISSUE TITLE
📊 Add Powerpoint slides for the project

### ISSUE THREAD

**Issue by KenjiPcx** [KenjiPcx/Diabot#24]
**Important**: We need this for demo day

Create presentation slides with the following format:
Project Demo with 2-3 slides with the following details
- What process did you go through to create your project?
- How did you choose what product / service to focus on?
- What changes would you make to this process for next time?
- What challenges did you face when creating this project? 
- How did you overcome those challenges?
- Recommendations you have for future teams of ambassadors working on projects

**Comment by maryem-ben-ali** [comment]
[demoday.pptx](https://github.com/KenjiPcx/Diabot/files/10254495/demoday.pptx)

**Comment by KenjiPcx** [comment]
Just saw the slides, we only need to explain briefly, 2-3 slides
Use these details
1. What process did you go through to create your project?
- We were not very experienced in medtech, so we just researched problems in general, our focus was not to make something completely new, but just for us to learn and build something, we chose diabetes because it is quite a popular topic
2. How did you choose what product / service to focus on?
- We wanted something that was doable with our experience, we tried out different ideas within the field of diabetes management appsound ended up making a carb logger app but with a twist, which is to do it using an intelligent bot interface
3. What changes would you make to this process for next time?
- Decide early on for the idea, it would be useful to have an experienced mentor
4. What challenges did you face when creating this project?
- Time constraints, everyone was busy and it was hard to sync
- Lost in general because medtech is a whole new field for us, felt like giving up a lot of times
5. How did you overcome those challenges?
- We just pushed through
- We asked people in the chat for advice
6. Recommendations you have for future teams of ambassadors working on projects
- Learn the capabilities of Azure before joining the project or else a lot of time will be wasted

**Comment by lahybris** [comment]
I agree with @KenjiPcx, the presentation should be just few slides.

**Comment by KenjiPcx** [comment]
@maryem-ben-ali  Push the updates to the powerpoint again please so we can close this issue
